### ISSUE TITLE
The download link does not work

### ISSUE THREAD

**Issue by lauraset** [whheda/Urban-Tree-Cover-Dataset-UTCD-#1]
Hello, @whheda, the link for downloading UTCD dataset seems not work. Can you check it？

**Comment by whheda** [comment]
Sorry for the failed link, it has just been repaired and now is available.



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月04日 15:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | [whheda/Urban-Tree-Cover-Dataset-UTCD-] Not find the UTCD dataset (Issue #1) |

Hello, @whheda, the link for downloading UTCD dataset seems not work. Can you check it？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lauraset** [comment]
Hello, @whheda , thank you very much. I learned a lot from your research.
